# Generated by Django 3.0.4 on 2020-03-13 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Troco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('troco', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_100', models.CharField(max_length=10)),
                ('nota_50', models.CharField(max_length=10)),
                ('nota_10', models.CharField(max_length=10)),
                ('nota_5', models.CharField(max_length=10)),
                ('nota_1', models.CharField(max_length=10)),
                ('troco_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troco.Troco')),
            ],
        ),
        migrations.CreateModel(
            name='Moedas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moeda_50', models.CharField(max_length=10)),
                ('moeda_10', models.CharField(max_length=10)),
                ('moeda_5', models.CharField(max_length=10)),
                ('moeda_1', models.CharField(max_length=10)),
                ('troco_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troco.Troco')),
            ],
        ),
    ]
