# Generated by Django 3.0.4 on 2020-03-13 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('troco', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moedas',
            new_name='Moeda',
        ),
        migrations.RenameModel(
            old_name='Notas',
            new_name='Nota',
        ),
    ]
