# Generated by Django 3.0.4 on 2020-03-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troco', '0003_auto_20200312_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='troco_index',
        ),
        migrations.AddField(
            model_name='troco',
            name='moeda_1',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='troco',
            name='moeda_10',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='troco',
            name='moeda_5',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='troco',
            name='moeda_50',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='troco',
            name='nota_1',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='troco',
            name='nota_10',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='troco',
            name='nota_100',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='troco',
            name='nota_5',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='troco',
            name='nota_50',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.DeleteModel(
            name='Moeda',
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
