# Generated by Django 2.2.11 on 2020-03-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troco', '0004_auto_20200312_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrocoCerto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('troco', models.CharField(max_length=10)),
                ('nota_100', models.CharField(default='0', max_length=10)),
                ('nota_50', models.CharField(default='0', max_length=10)),
                ('nota_10', models.CharField(default='0', max_length=10)),
                ('nota_5', models.CharField(default='0', max_length=10)),
                ('nota_1', models.CharField(default='0', max_length=10)),
                ('moeda_50', models.CharField(default='0', max_length=10)),
                ('moeda_10', models.CharField(default='0', max_length=10)),
                ('moeda_5', models.CharField(default='0', max_length=10)),
                ('moeda_1', models.CharField(default='0', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Troco',
        ),
    ]
